version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

#  telegraf:
#    image: telegraf:1.19
#    volumes:
#      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
#    env_file:
#      - .env
#    depends_on:
#      - influxdb

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - homeassistant-config:/var/lib/home-assistant/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    depends_on:
      - influxdb

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    depends_on:
      - influxdb
    volumes:
      - nodered-storage:/var/lib/node-red/data

volumes:
  grafana-storage:
  influxdb-storage:
  homeassistant-config:
  nodered-storage:
