version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - ${BASE_PATH}/influxdb:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

#  telegraf:
#    image: telegraf:1.19
#    volumes:
#      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
#    env_file:
#      - .env
#    depends_on:
#      - influxdb

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - ${BASE_PATH}/home-assistant/config:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${BASE_PATH}/home-assistant/config:/var/lib/home-assistant/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    depends_on:
      - influxdb

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    depends_on:
      - influxdb
    volumes:
      - ${BASE_PATH}/node-red/data:/var/lib/node-red/data

  mosquitto:
    image: eclipse-mosquitto
    depends_on:
      - influxdb
    volumes:
      - ${BASE_PATH}/mosquitto:/mosquitto
      - ${BASE_PATH}/mosquitto/data:/mosquitto/data
      - ${BASE_PATH}/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

